[cicd] Add VPN connection again

diff --git a/.github/workflows/2_continuous_delivery.yml b/.github/workflows/2_continuous_delivery.yml
--- a/.github/workflows/2_continuous_delivery.yml
+++ b/.github/workflows/2_continuous_delivery.yml
@@ -44,6 +44,26 @@ jobs:
       - name: Pull models image
         run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}/models:${{ github.sha }}
 
+      - name: Install OpenVPN
+        run: |
+          sudo apt update
+          sudo apt install -y openvpn openvpn-systemd-resolved
+
+      - name: Create OVPN file
+        run: echo "${{ secrets.OVPN_CONFIG_FILE }}" > DEI.ovpn
+
+      - name: Connect to VPN
+        uses: "kota65535/github-openvpn-connect-action@v3"
+        with:
+          config_file: DEI.ovpn
+          username: ${{ secrets.OVPN_USERNAME }}
+          password: ${{ secrets.OVPN_PASSWORD }}
+
+      - name: Ping test
+        run: |
+          set -x
+          ping -c 4 ${{ secrets.SERVING_VM_HOST }} || echo "ping failed with code $?"
+
       # Run models container which runs the models script within
       # The models script will select the "best" model and tag it with the sha of the commit in mlflow
       - name: Run models
