[cicd] Add DEI VPN connection

diff --git a/.github/workflows/2_continuous_delivery.yml b/.github/workflows/2_continuous_delivery.yml
--- a/.github/workflows/2_continuous_delivery.yml
+++ b/.github/workflows/2_continuous_delivery.yml
@@ -41,6 +41,30 @@ jobs:
       # Download models image built in the previous stage
       - run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}/models:${{ github.sha }}
 
+      # ===================== Setup VPN to access DEI network =====================
+      # Install VPN client
+      - name: Install OpenVPN
+        run: |
+          sudo apt update
+          sudo apt install -y openvpn openvpn-systemd-resolved
+      # Connect to the VPN using the provided OVPN config and secrets
+      - name: Connect to VPN
+        uses: "kota65535/github-openvpn-connect-action@v2"
+        with:
+          config_file: ${{ secrets.OVPN_CONFIG_FILE }}
+          username: ${{ secrets.OVPN_USERNAME }}
+          password: ${{ secrets.OVPN_PASSWORD }}
+      # Verify VPN connection
+      - name: Verify VPN connection
+        # ">/dev/null 2>&1" is used to suppress output. We only care if the command succeeds or fails
+        run: |
+          if ip addr show tun0 >/dev/null 2>&1; then
+            echo "VPN is up."
+          else
+            echo "VPN is NOT up. Exiting."
+            exit 1
+          fi
+
       # Run models container which runs the models script within
       # The models script will select the "best" model and tag it with the sha of the commit in mlflow
       - name: Run models
