[cicd] Add VPN connection

diff --git a/.github/workflows/4_continuous_deployment.yml b/.github/workflows/4_continuous_deployment.yml
--- a/.github/workflows/4_continuous_deployment.yml
+++ b/.github/workflows/4_continuous_deployment.yml
@@ -42,6 +42,26 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}/serving:production
+
+      # ===================== Setup VPN to access DEI network =====================
+      # Connect to the VPN using the provided OVPN config and secrets
+      - name: Connect to VPN
+        uses: "kota65535/github-openvpn-connect-action@v2"
+        with:
+          config_file: ${{ secrets.OVPN_CONFIG_FILE }}
+          username: ${{ secrets.OVPN_USERNAME }}
+          password: ${{ secrets.OVPN_PASSWORD }}
+      # Verify VPN connection
+      - name: Verify VPN connection
+        # ">/dev/null 2>&1" is used to suppress output. We only care if the command succeeds or fails
+        run: |
+          if ip addr show tun0 >/dev/null 2>&1; then
+            echo "VPN is up."
+          else
+            echo "VPN is NOT up. Exiting."
+            exit 1
+          fi
+
       - run: docker stop serving-app || true
       - run: docker rm serving-app || true
 
